name: Node Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Build
        run: npm install
      - run: npm run build chrome
      - run: npm run build firefox
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages
