name: Node Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm i -g npm
          npm install
          npm run build chrome
          npm run build firefox
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages
